title: Xiaotong Jiang's Homepage
page-top-title: Xiaotong Jiang
top-section-bg-text: Computer Control and Automation
home-subtitle: Xiaotong Jiang&ensp;|&ensp;江
copyright-text: '&copy; Xiaotong Jiang 2023-2024. All Rights Reserved.'
